# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-05T13:45:13+00:00
#   source: antiSMASH repository (master branch)
#   commit: 87d1a9bf280dd8b61e5ca86a6c2ec7bf2cc83f22
#   commit_date: 2020-12-04T08:07:47Z
#   commit_msg: sideloader: add module for importing external annotations

from __future__ import annotations

from typing import Annotated, Dict, List, Optional, Union

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Details1(RootModel[str]):
    root: Annotated[str, Field(min_length=1, pattern="^[^\\s_=,].*$")]


class Details2Item(RootModel[str]):
    root: Annotated[str, Field(min_length=1, pattern="^[^\\s_=,].*$")]


class Details2(RootModel[List[Details2Item]]):
    root: Annotated[List[Details2Item], Field(min_length=1)]


class Details(RootModel[Dict[str, Union[Details1, Details2]]]):
    root: Dict[str, Union[Details1, Details2]]


class Subregion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Annotated[int, Field(description="The start of the region within the record", ge=0)]
    end: Annotated[int, Field(description="The end of the region within the record", ge=1)]
    label: Annotated[
        str,
        Field(
            description="The label to give the region",
            examples=["Polyketide", "Type I PKS"],
            max_length=20,
            pattern="^(.+)$",
        ),
    ]
    details: Optional[Details] = None


class Protocluster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    core_start: Annotated[
        int,
        Field(description="The start of the protocluster core within the record", ge=0),
    ]
    core_end: Annotated[
        int,
        Field(description="The end of the protocluster core within the record", ge=1),
    ]
    product: Annotated[
        str,
        Field(
            description="The predicted product of the protocluster, for antiSMASH analyses to run, the product must be as antiSMASH would predict",
            examples=["NRPS", "T2PKS"],
            max_length=20,
            min_length=2,
            pattern="^(.+)$",
        ),
    ]
    neighbourhood_left: Annotated[
        Optional[int],
        Field(description="the area to the left of the core to include in analyses", ge=0),
    ] = 0
    neighbourhood_right: Annotated[
        Optional[int],
        Field(description="the area to the right of the core to include in analyses", ge=0),
    ] = 0
    details: Optional[Details] = None


class Tool(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(description="The name of the tool", pattern="^(.+)$")]
    version: Annotated[Optional[str], Field(description="The version of the tool", pattern="^(.+)$")] = None
    description: Annotated[
        Optional[str],
        Field(
            description="A simple description of the tool or it's configuration",
            pattern="^(.+)$",
        ),
    ] = None
    configuration: Annotated[
        Optional[Details],
        Field(description="Specifics of the tool's configuration, if relevant"),
    ] = None


class Record(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(description="The record identifier containing the areas", pattern="^(.+)$"),
    ]
    subregions: Annotated[Optional[List[Subregion]], Field(description="Subregions to add to the record")] = None
    protoclusters: Annotated[
        Optional[List[Protocluster]],
        Field(description="Protoclusters to add to the record"),
    ] = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool: Tool
    records: Annotated[List[Record], Field(description="The Records Schema", min_length=1)]
    timestamp: Annotated[
        Optional[AwareDatetime],
        Field(
            description="The time these results were created (in ISO8601 format)",
            examples=["2019-04-27T13:45:00+02:00"],
        ),
    ] = None
